#!/usr/bin/env bash

#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls.py --root ../data/kaggle/512 --traincsv ../data/kaggle/train_multi.csv --valcsv ../data/kaggle/val_multi.csv --testcsv ../data/kaggle/test_bin.csv --model rsn34 --batch 64 --workers 8 --epoch 100 --display 50

#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls.py --root ../data/dme/512 --traincsv ../data/dme/train_multi.csv --valcsv ../data/dme/val_multi.csv --testcsv ../data/dme/test_bin.csv --model rsn34 --batch 64 --workers 8 --epoch 100 --display 50

#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls.py --root ../data/kaggle/512 --traincsv ../data/kaggle/train_multi.csv --valcsv ../data/kaggle/val_multi.csv --testcsv ../data/kaggle/val_multi.csv --model rsn34 --batch 32 --workers 8 --epoch 100 --display 50 --phase test --crop 512 --size 512 --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170911155819_rsn34_multi_task/kaggle_multi_task_cls_dr_rsn34_015_best.pth

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 8 --epoch 100 --display 50

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/data_multi.csv --model rsn34 --batch 32 --workers 8 --epoch 100 --display 50 --crop 512 --size 512 --weight ./kaggle_multi_task_cls_dr_rsn34_012_best.pth --phase test

#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls.py --root ../data/dme/512 --traincsv ../data/dme/train_multi.csv --valcsv ../data/dme/val_multi.csv --testcsv ../data/dme/train_multi.csv --model rsn34 --batch 32 --workers 8 --epoch 100 --display 50 --crop 512 --size 512 --weight ./output/kaggle_multi_task_cls_train_20170911202411_rsn34_multi_task/kaggle_multi_task_cls_dr_rsn34_021_best.pth --phase test

#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls.py --root ../data/kaggle/512 --traincsv ../data/kaggle/train_multi.csv --valcsv ../data/kaggle/val_multi.csv --testcsv ../data/kaggle/train_multi.csv --model rsn34 --batch 32 --workers 8 --epoch 100 --display 50 --crop 512 --size 512 --weight ./output/kaggle_multi_task_cls_train_20170911202411_rsn34_multi_task/kaggle_multi_task_cls_dr_rsn34_021_best.pth --phase test


#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/data_multi.csv --model rsn34 --batch 200 --workers 8 --epoch 150 --display 50 --crop 448 --size 512

#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls.py --root ../data/kaggle/512 --traincsv ../data/kaggle/train_multi.csv --valcsv ../data/kaggle/val_multi.csv --testcsv ../data/kaggle/test_multi.csv --model dsn121 --batch 8 --workers 4 --epoch 100 --display 50

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model dsn121 --batch 16 --workers 4 --epoch 150 --display 50 --crop 448 --size 512 --weigh /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170912195752_dsn121_multi_task/kaggle_multi_task_cls_dr_dsn121_017_best.pth

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/val_multi.csv --model dsn121 --batch 16 --workers 4 --epoch 150 --display 50 --crop 448 --size 512 --weigh /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170912195752_dsn121_multi_task/kaggle_multi_task_cls_dr_dsn121_017_best.pth --phase test

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 150 --display 50 --crop 448 --size 512

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 150 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls


#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 150 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170914195436_rsn34_concatenation_bin_cls/kaggle_multi_task_cls_concatenation_binary_rsn34_007_best.pth --phase test
#
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 150 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170914195436_rsn34_concatenation_bin_cls/kaggle_multi_task_cls_dr_rsn34_025_best.pth --phase test
#
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 150 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170914195436_rsn34_concatenation_bin_cls/kaggle_multi_task_cls_dme_rsn34_018_best.pth --phase test


### refer

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 150 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170914195436_rsn34_concatenation_bin_cls/kaggle_multi_task_cls_dr_rsn34_025_best.pth --phase infer --infer_root ../data/zhizhen_new/inference


### train

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_dme_aug --dme_weight_aug 8.0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug

### test
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 16 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase test


### infer
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 16 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen/image_0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 16 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen/image_1
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 16 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen/image_2
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 16 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen/image_3
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 16 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen/image_4

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/1
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/2
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/3
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20170916115950_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_019_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/image

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171212082541_rsn34_clean_0/kaggle_multi_task_cls_dr_rsn34_008_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171212082541_rsn34_clean_0/kaggle_multi_task_cls_dr_rsn34_008_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/1
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171212082541_rsn34_clean_0/kaggle_multi_task_cls_dr_rsn34_008_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/2
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171212082541_rsn34_clean_0/kaggle_multi_task_cls_dr_rsn34_008_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/3
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171212082541_rsn34_clean_0/kaggle_multi_task_cls_dr_rsn34_008_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/4
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171212082541_rsn34_clean_0/kaggle_multi_task_cls_dr_rsn34_008_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/image



#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/tmp/del34/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/tmp/del34/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/tmp/del34/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug

#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171207131126_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_003_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/image
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171207131126_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_003_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/1
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp concatenation_bin_cls_none_dme_aug --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171207131126_rsn34_concatenation_bin_cls_none_dme_aug/kaggle_multi_task_cls_dr_rsn34_003_best.pth --phase infer --infer_root /home/weidong/data/zhizhen_test/data-171205/2
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv ../data/zhizhen_new/LabelImages/train_multi.csv --valcsv ../data/zhizhen_new/LabelImages/val_multi.csv --testcsv ../data/zhizhen_new/LabelImages/test_multi.csv --model rsn34


#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/tmp/del34_danyu_1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/tmp/del34_danyu_1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/tmp/del34_danyu_1211/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_0 --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171208160309_rsn34_clean_0/kaggle_multi_task_cls_dme_rsn34_001_best.pth --phase infer --infer_root /home/weidong/data/sort_image/pure
#CUDA_VISIBLE_DEVICES=0,1,2,3 python single_channel_multi_task_cls_concatenate.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_0 --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20171208160309_rsn34_clean_0/kaggle_multi_task_cls_dme_rsn34_001_best.pth --phase infer --infer_root /home/weidong/data/sort_image/NormalData


#cp /home/weidong/data/zhizhen_test/data-171205/0/result.csv /home/weidong/data/zhizhen_test/result_danyu_1212/0.result
#cp /home/weidong/data/zhizhen_test/data-171205/1/result.csv /home/weidong/data/zhizhen_test/result_danyu_1212/1.result
#cp /home/weidong/data/zhizhen_test/data-171205/2/result.csv /home/weidong/data/zhizhen_test/result_danyu_1212/2.result
#cp /home/weidong/data/zhizhen_test/data-171205/3/result.csv /home/weidong/data/zhizhen_test/result_danyu_1212/3.result
#cp /home/weidong/data/zhizhen_test/data-171205/4/result.csv /home/weidong/data/zhizhen_test/result_danyu_1212/4.result
#cp /home/weidong/data/zhizhen_test/image/result.csv /home/weidong/data/zhizhen_test/result_danyu_1212/jianbin.result



#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1214/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1214/test_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1214/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort19_finish/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort10/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort11/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort12/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort13/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort14/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort15/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort16/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort17/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort18/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort9/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort8/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort7/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort6/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort5/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort4/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort3/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort1/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215111128_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_022_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort0/0



#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort10/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort11/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort12/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort13/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort14/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort15/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort16/0
CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort17/0
CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort18/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort9/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort8/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort7/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort6/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort5/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort4/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort3/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort1/0
#CUDA_VISIBLE_DEVICES=0,1,2,3 python binary_for_select_from_0.py --root ../data/zhizhen_new/LabelImages/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/screen_flag_danyu1211/test_multi.csv --model rsn18 --batch 64 --workers 4 --epoch 80 --display 50 --crop 448 --size 512 --exp clean_fffffffffff --weight ./output/kaggle_multi_task_cls_train_20171215080858_rsn18_clean_fffffffffff/kaggle_multi_task_cls_concatenation_binary_rsn18_009_best.pth --phase infer --infer_root /home/weidong/data/sort_image1/sort0/0