#!/usr/bin/env bash

#CUDA_VISIBLE_DEVICES=0 python multi_fundus_disease.py --root /media/weidong/weidong/分类眼底病/512 --traincsv /media/weidong/weidong/分类眼底病/label/train_multi.csv --valcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --testcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp multi_disease_cls

CUDA_VISIBLE_DEVICES=0 python multi_fundus_disease.py --root /media/weidong/weidong/分类眼底病/512 --traincsv /media/weidong/weidong/分类眼底病/label/train_multi.csv --valcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --testcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp multi_disease_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180209142329_rsn34_multi_disease_cls/kaggle_multi_fundus_disease_rsn34_003_best.pth --phase infer --infer_root /media/weidong/weidong/分类眼底病/中浆/test
CUDA_VISIBLE_DEVICES=0 python multi_fundus_disease.py --root /media/weidong/weidong/分类眼底病/512 --traincsv /media/weidong/weidong/分类眼底病/label/train_multi.csv --valcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --testcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp multi_disease_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180209142329_rsn34_multi_disease_cls/kaggle_multi_fundus_disease_rsn34_003_best.pth --phase infer --infer_root /media/weidong/weidong/分类眼底病/有髓神经纤维/test
CUDA_VISIBLE_DEVICES=0 python multi_fundus_disease.py --root /media/weidong/weidong/分类眼底病/512 --traincsv /media/weidong/weidong/分类眼底病/label/train_multi.csv --valcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --testcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp multi_disease_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180209142329_rsn34_multi_disease_cls/kaggle_multi_fundus_disease_rsn34_003_best.pth --phase infer --infer_root /media/weidong/weidong/分类眼底病/视网膜中央动脉阻塞/test
CUDA_VISIBLE_DEVICES=0 python multi_fundus_disease.py --root /media/weidong/weidong/分类眼底病/512 --traincsv /media/weidong/weidong/分类眼底病/label/train_multi.csv --valcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --testcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp multi_disease_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180209142329_rsn34_multi_disease_cls/kaggle_multi_fundus_disease_rsn34_003_best.pth --phase infer --infer_root /media/weidong/weidong/分类眼底病/视网膜中央静脉阻塞/test
CUDA_VISIBLE_DEVICES=0 python multi_fundus_disease.py --root /media/weidong/weidong/分类眼底病/512 --traincsv /media/weidong/weidong/分类眼底病/label/train_multi.csv --valcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --testcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp multi_disease_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180209142329_rsn34_multi_disease_cls/kaggle_multi_fundus_disease_rsn34_003_best.pth --phase infer --infer_root /media/weidong/weidong/分类眼底病/视网膜分支静脉阻塞/test
CUDA_VISIBLE_DEVICES=0 python multi_fundus_disease.py --root /media/weidong/weidong/分类眼底病/512 --traincsv /media/weidong/weidong/分类眼底病/label/train_multi.csv --valcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --testcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp multi_disease_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180209142329_rsn34_multi_disease_cls/kaggle_multi_fundus_disease_rsn34_003_best.pth --phase infer --infer_root /media/weidong/weidong/分类眼底病/黄斑前膜/test
CUDA_VISIBLE_DEVICES=0 python multi_fundus_disease.py --root /media/weidong/weidong/分类眼底病/512 --traincsv /media/weidong/weidong/分类眼底病/label/train_multi.csv --valcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --testcsv /media/weidong/weidong/分类眼底病/label/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp multi_disease_cls --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180209142329_rsn34_multi_disease_cls/kaggle_multi_fundus_disease_rsn34_003_best.pth --phase infer --infer_root /media/weidong/weidong/分类眼底病/黄斑病变/test