#!/usr/bin/env bash

#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 15 --display 50 --crop 448 --size 512 --exp 180110_xxx

#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 15 --display 50 --crop 448 --size 512 --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180110200856_rsn34_180110_xxx/kaggle_multi_task_cls_dr_rsn34_010_best.pth --phase infer --infer_root /media/weidong/weidong/12.15质检图片/other --exp other_xxx


#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp 180110_xxx_inner_mix01
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp 180110_xxx_inner_mix02
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp 180110_xxx_inner_mix12


#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180112183518_rsn34_180110_xxx_inner_mix01/kaggle_multi_task_cls_dr_rsn34_008_best.pth --phase infer --infer_root /media/weidong/weidong/12.15质检图片/train_b/2 --exp 180110_xxx_inner_mix01
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180112202753_rsn34_180110_xxx_inner_mix02/kaggle_multi_task_cls_dr_rsn34_007_best.pth --phase infer --infer_root /media/weidong/weidong/12.15质检图片/train_b/1 --exp 180110_xxx_inner_mix02
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180112221615_rsn34_180110_xxx_inner_mix12/kaggle_multi_task_cls_dr_rsn34_005_best.pth --phase infer --infer_root /media/weidong/weidong/12.15质检图片/train_b/0 --exp 180110_xxx_inner_mix12


#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 15 --display 50 --crop 448 --size 512 --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180110200856_rsn34_180110_xxx/kaggle_multi_task_cls_dr_rsn34_010_best.pth --phase infer --infer_root /media/weidong/weidong/test_a/all --exp other_a

#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180112183518_rsn34_180110_xxx_inner_mix01/kaggle_multi_task_cls_dr_rsn34_008_best.pth --phase infer --infer_root /media/weidong/weidong/12.15质检图片/train_a/2 --exp 180110_xxx_inner_mix01
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180112202753_rsn34_180110_xxx_inner_mix02/kaggle_multi_task_cls_dr_rsn34_007_best.pth --phase infer --infer_root /media/weidong/weidong/12.15质检图片/train_a/1 --exp 180110_xxx_inner_mix02
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180112221615_rsn34_180110_xxx_inner_mix12/kaggle_multi_task_cls_dr_rsn34_005_best.pth --phase infer --infer_root /media/weidong/weidong/12.15质检图片/train_a/0 --exp 180110_xxx_inner_mix12

#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /media/weidong/weidong/AB迭代/train/mix01_train_multi.csv --valcsv /media/weidong/weidong/AB迭代/train/mix01_val_multi.csv --testcsv /media/weidong/weidong/AB迭代/train/mix01_test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp 180123_xxx_inner_mix01
#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /media/weidong/weidong/AB迭代/train/mix02_train_multi.csv --valcsv /media/weidong/weidong/AB迭代/train/mix02_val_multi.csv --testcsv /media/weidong/weidong/AB迭代/train/mix02_test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp 180123_xxx_inner_mix02
#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /media/weidong/weidong/AB迭代/train/mix12_train_multi.csv --valcsv /media/weidong/weidong/AB迭代/train/mix12_val_multi.csv --testcsv /media/weidong/weidong/AB迭代/train/mix12_test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp 180123_xxx_inner_mix12

#CUDA_VISIBLE_DEVICES=0,1 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /media/weidong/weidong/AB迭代/train/train_multi.csv --valcsv /media/weidong/weidong/AB迭代/train/val_multi.csv --testcsv /media/weidong/weidong/AB迭代/train/test_multi.csv --model rsn34 --batch 64 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --exp 180123_xxx_inner


#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180123193507_rsn34_180123_xxx_inner_mix01/best_dr.pth --phase infer --infer_root /media/weidong/weidong/AB迭代/train/2 --exp 180123_xxx_inner_mix01
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix02_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180123204244_rsn34_180123_xxx_inner_mix02/best_dr.pth --phase infer --infer_root /media/weidong/weidong/AB迭代/train/1 --exp 180123_xxx_inner_mix02
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180123214649_rsn34_180123_xxx_inner_mix12/best_dr.pth --phase infer --infer_root /media/weidong/weidong/AB迭代/train/0 --exp 180123_xxx_inner_mix12
#
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180123225243_rsn34_180123_xxx_inner/best_dr.pth --phase infer --infer_root /media/weidong/weidong/AB迭代/test_b（原始结果） --exp 180123_xxx_inner
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180123225243_rsn34_180123_xxx_inner/best_dr.pth --phase infer --infer_root /media/weidong/weidong/AB迭代/test_a（原始结果）/all --exp 180123_xxx_inner


# 0
# CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix12_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180123225243_rsn34_180123_xxx_inner/best_dr.pth --phase infer --infer_root /media/weidong/seagate_data/dataset/IDRID/IDRID_2/TrainingSet --exp 180123_xxx_inner
# 1
#CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx_inner/mix01_test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 30 --display 50 --crop 448 --size 512 --weight ./output/kaggle_multi_task_cls_train_20180123193507_rsn34_180123_xxx_inner_mix01/best_dr.pth --phase infer --infer_root /media/weidong/seagate_data/dataset/IDRID/IDRID_2/TrainingSet --exp 180123_xxx_inner_mix01
# 2
CUDA_VISIBLE_DEVICES=0 python single_channel_multi_task_cls_concatenate.py --root /media/weidong/weidong/512 --traincsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/train_multi.csv --valcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/val_multi.csv --testcsv /home/weidong/code/kaggle/kaggle_mecari_price_challenge/screening/xxx/test_multi.csv --model rsn34 --batch 32 --workers 4 --epoch 15 --display 50 --crop 448 --size 512 --weight /home/weidong/code/github/DiabeticRetinopathy_solution/paper_data/output/kaggle_multi_task_cls_train_20180110200856_rsn34_180110_xxx/kaggle_multi_task_cls_dr_rsn34_010_best.pth --phase infer --infer_root '/media/weidong/seagate_data/dataset/IDRID_new/IDRID_2/Training Set' --exp other_xxx



